# This is a basic workflow to help you get started with Actions

name: Formal Verification

# Controls when the workflow will run
on:
  # Launch when modifications to the code folder are pushed
  push:
    paths:
    - code/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  formal-verif:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      SRC_FOLDER: "code"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Find all .sby scripts in all subfolders of code/ and run them in the parent folder of the script
      - name: Run Formal Verif
        run: |
          cd ${SRC_FOLDER}
          for sby_path in $(find . -iname "*.sby"); do 
              sby_script=${sby_path##*/}
              cd ${sby_path%/*}
              #sby --prefix ../verif_out/ --yosys "yosys -m ghdl" -f $sby_script
              echo $sby_script
              # ^
              cd -
          done
